### PR TITLE
fix #115

### LINKED ISSUE #115: Line intersect detection fails sometimes
There seems to be a bug in the line intersect code.

A specific failure case is 

``` 
using GeometryTypes
l = LineSegment(Point(6.0,11), Point(12.0,11))

r1 = GeometryTypes.LineSegment( Point(9.0,10.0), Point(9.0, 13.0))
r2 = GeometryTypes.LineSegment( Point(9.34365, 10.890), Point(9.34365, 13.402))
```

```
julia> intersects(l, r1)
(true, [9.0, 11.0])

julia> intersects(l, r2)
(false, [0.0, 0.0])
```
I would expect that the second case would return true as well.

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

File: src/lines.jl [hunk 1]
```diff
@@ -38,10 +38,10 @@ function intersects(a::LineSegment{Point{N,T}}, b::LineSegment{Point{N,T}}) wher
...
     y = det(MT(d1, v1[2] - v2[2], d2, v3[2] - v4[2])) / a;
 
-    (x < min(v1[1], v2[1]) - eps(T) || x > max(v1[1], v2[1]) + eps(T)) && return false, p0
-    (y < min(v1[2], v2[2]) - eps(T) || y > max(v1[2], v2[2]) + eps(T)) && return false, p0
-    (x < min(v3[1], v4[1]) - eps(T) || x > max(v3[1], v4[1]) + eps(T)) && return false, p0
-    (y < min(v3[2], v4[2]) - eps(T) || y > max(v3[2], v4[2]) + eps(T)) && return false, p0
+    (x < prevfloat(min(v1[1], v2[1])) || prevfloat(x) > max(v1[1], v2[1]) + eps(T)) && return false, p0
+    (y < prevfloat(min(v1[2], v2[2])) || prevfloat(y) > max(v1[2], v2[2]) + eps(T)) && return false, p0
+    (x < prevfloat(min(v3[1], v4[1])) || prevfloat(x) > max(v3[1], v4[1]) + eps(T)) && return false, p0
+    (y < prevfloat(min(v3[2], v4[2])) || prevfloat(y) > max(v3[2], v4[2]) + eps(T)) && return false, p0
```
Comment (visr) [inline src/lines.jl]: It seems you forgot to remove the ` + eps(T)` in the second part. And perhaps this would be more consistent?
```julia
x < prevfloat(min(...)) || x > nextfloat(max(...))
```

Comment (SimonDanisch) [reply src/lines.jl]: Oh yes, thanks! I shouldn't create PRs when I don't actually have any time...

**Comment by visr** [comment]
:+1: 
This might related to the accuracy of `det`, which people happen to be discussing right now on discourse:
https://discourse.julialang.org/t/accuracy-of-computing-determinants/6782
